spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/poc?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password:
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    driver-class-name: com.mysql.cj.jdbc.Driver